export const groupIngredientsMap: Record<string, string[]> = {
  vegetables: [
    "corn",
    "crispy_onion",
    "bell_pepper",
    "onion",
    "sun_dried_tomatoes",
    "mustard",
    "tomatoes",
    "pickled_cucumbers",
    "spinach",
    "cherry_tomatoes",
    "olives",
    "mushrooms",
    "pear",
    "jalapeno",
    "pineapple",
  ],
  meat: [
    "white_sausages",
    "pepperoni",
    "bavarian_sausages",
    "bacon",
    "ham",
    "salami",
    "chicken",
    "tuna",
    "meatballs",
    "veal",
    "chorizo",
    "turkey",
  ],
  sauces: ["dominos_sauce", "alfredo_sauce", "garlic_sauce", "bbq_sauce"],
  cheese: ["cheddar", "feta", "parmesan", "bergader_blue", "mozzarella"],
  sweet: ["banana", "almond", "choco_paste"],
};
